CREATE TABLE IF NOT EXISTS Users (
    discord_id INTEGER NOT NULL UNIQUE PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    nickname TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Configs (
    channel_config_code TEXT NOT NULL UNIQUE,
    channel_id INTEGER NOT NULL DEFAULT 0
);